### ISSUE TITLE
Button 2 sharing SDA line: is this ok?

### ISSUE THREAD

**Issue by piecol** [sb-ocr/diy-spacemouse#10]
Hi,

thanks for sharing this cool design!
I did not test the product yet, still waiting for components to arrive.

This is more of a question.. while I was going through the document of the buttons' wiring I notices you assigned button2 to pin 24, which happens to be the SDA line. Isn't it going to conflict with the TLV493D operation? 
 ```c
// Setup buttons
OneButton button1(27, true);
OneButton button2(24, true);
 ```

![wiring](https://github.com/sb-ocr/diy-spacemouse/assets/29545872/696d072c-ce79-4c8a-a0dd-1feffe43b4fd)

**Comment by sb-ocr** [comment]
Hi, 

There are 2 I2C buses on the RP2040. The one connected to the button is not used to communicate with the TLV493D. It just happened to be closer when I was soldering the wires; there is no particular reason for choosing that pin.
<img width="1497" alt="Screenshot 2023-07-07 at 9 48 53 AM" src="https://github.com/sb-ocr/diy-spacemouse/assets/99417980/3b25f84c-2b96-426a-afd8-7786170c286f">
