### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by gregoryleblanc** [sb-ocr/diy-spacemouse#13]
Any chance you'd be willing to license this as CC-BY-SA?  I'd like to use it as a starting point to see if we can get to 6 DOF, and your design is far better than anything else out there.
https://creativecommons.org/licenses/by-sa/4.0/

**Comment by sb-ocr** [comment]
Thanks! I've forgot to upload the license to Github but it's on the Instructables. It's under CC-BY-NC-SA 
You are free to change this in any manner you want as long as it's for non commercial.
