### ISSUE TITLE
TinyUSB_Mouse_and_Keyboard.h

### ISSUE THREAD

**Issue by maranhaoBruno** [sb-ocr/diy-spacemouse#15]
Where did you find TinyUSB_Mouse_and_Keyboard.h? I was able to install all the other libraries directly from the Arduino IDE except for this one. I found and installed this (https://github.com/cyborg5/TinyUSB_Mouse_and_Keyboard), but now I'm getting a fatal error that there is no HID.h. I thought I'd ask for help before going down a Depp deep rabbit hole.

Thanks,
B

**Comment by sb-ocr** [comment]
That seem to be the correct one, you also have to change the USB stack to TinyUSB.
Check the usage section in this guide:
https://learn.adafruit.com/mouse-and-keyboard-control-using-tinyusb-and-ble/installing-the-libraries
