### ISSUE TITLE
Fusion file?

### ISSUE THREAD

**Issue by jdugan1024** [sb-ocr/diy-spacemouse#19]
Hello,

Thank you for making this and sharing it. I've started assembling one and am looking forward to giving it a try. 

I've run into a small snag. The threaded inserts I have are a little smaller in diameter than the ones you used. I thought hey, no problem there's a step file I can just tweak it. And that's true to an extent but editing a step file is not nearly as straightforward as editing the equivalent Fusion 360 file. 

Would you be willing to include the Fusion file to the GitHub repository?

Thanks again for all your work in documenting and sharing this.

**Comment by sb-ocr** [comment]
Hi, Checkout the Fusion embeds in the Instructables. It allows you to download in several formats Fusion Archive included.
