### ISSUE TITLE
CAD files

### ISSUE THREAD

**Issue by MohrJonas** [sb-ocr/diy-spacemouse#2]
Hi would it be possible to upload step files of the components, rather than just stls?
Thanks

**Comment by MohrJonas** [comment]
Alright I added some crude STEP files. These are generated from the provided STLs and are therefore a bit rough, but should still be sufficient for most things https://github.com/MohrJonas/diy-spacemouse

**Comment by sb-ocr** [comment]
Hi, I uploaded the [STEP](https://github.com/sb-ocr/diy-spacemouse/tree/main/CAD) file if you still need it.

**Comment by MohrJonas** [comment]
Amazing thanks a lot 😀
