### ISSUE TITLE
BOM

### ISSUE THREAD

**Issue by CyborgGearVR** [sb-ocr/diy-spacemouse#3]
Please include a Bill of Materials when you add your Build Instructions.  That way we can purchase the same springs and boards you did,  Thanks.

**Comment by jrsall92** [comment]
I made a BOM and a pull request, in the mean time until it's accepted, you can find it here https://github.com/sb-ocr/diy-spacemouse/pull/4

**Comment by mpx1986** [comment]
Can you please add the size of the magnets

**Comment by sb-ocr** [comment]
> I made a BOM and a pull request, in the mean time until it's accepted, you can find it here #4

Thanks! I was already working on this update. I uploaded the exact parts and hardware [BOM](https://github.com/sb-ocr/diy-spacemouse/tree/main/BOM)

**Comment by CyborgGearVR** [comment]
Thank you for the quick action on this.  Starting to work on one now.

**Comment by TheUltimateAbsol** [comment]
BOM not clear on the screws and heatsets, see https://github.com/sb-ocr/diy-spacemouse/issues/9
